---

# configuring server sites

- name: write site configuration
  become: yes
  template:
    src: "{{ item.template | default('site.conf.j2') }}"
    dest: "/etc/nginx/sites.d/{{ item.label }}.conf"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: "0644"
  with_items: "{{ nginx_sites }}"
  notify: nginx - restart
